version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  main-service:
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - redis

  provider-service:
    build: ./provider-service
    depends_on:
      - redis
